command_bus:
    command_bus:
        middlewares:
            - Apisearch\Server\Domain\Middleware\ExceptionsMiddleware
            - Apisearch\Server\Domain\Middleware\RepositoryReferenceMiddleware
            - Apisearch\Server\Domain\Middleware\TokenEndpointPermissionsLimitationMiddleware
            - Apisearch\Server\Domain\Plugin\PluginMiddlewareCollector
            - Apisearch\Server\Domain\Middleware\ComplexFields\IndexComplexFieldsMiddleware
            - Apisearch\Server\Domain\Middleware\ComplexFields\ResetOrDeleteIndexComplexFieldsMiddleware

    query_bus:
        middlewares:
            - Apisearch\Server\Domain\Middleware\ExceptionsMiddleware
            - Apisearch\Server\Domain\Middleware\RepositoryReferenceMiddleware
            - Apisearch\Server\Domain\Middleware\CheckIndexAvailabilityMiddleware
            - Apisearch\Server\Domain\Middleware\CheckHealthEventsQueueMiddleware
            - Apisearch\Server\Domain\Middleware\TokenQueryMiddleware
            - Apisearch\Server\Domain\Middleware\DefaultQueryValuesMiddleware
            - Apisearch\Server\Domain\Middleware\CheckHealthPluginsMiddleware
            - Apisearch\Server\Domain\Middleware\ItemToLineExportMiddleware
            - Apisearch\Server\Domain\Plugin\PluginMiddlewareCollector
            - Apisearch\Server\Domain\Middleware\ComplexFields\QueryComplexFieldsMiddleware
            - Apisearch\Server\Domain\Middleware\ComplexFields\GetIndicesComplexFieldsMiddleware
            - Apisearch\Server\Domain\Middleware\ComplexFields\ExportComplexFieldsMiddleware
            - Apisearch\Server\Domain\Middleware\GetIndicesMetadataMiddleware