command_bus:
    command_bus:
        middlewares:
            - Apisearch\Server\Domain\Middleware\ExceptionsMiddleware
            - Apisearch\Server\Domain\Middleware\RepositoryReferenceMiddleware
            - Apisearch\Server\Domain\Middleware\ComplexFields\IndexComplexFieldsMiddleware
            - Apisearch\Server\Domain\Middleware\ComplexFields\ResetOrDeleteIndexComplexFieldsMiddleware
            - Apisearch\Server\Domain\Plugin\PluginMiddlewareCollector

    query_bus:
        middlewares:
            - Apisearch\Server\Domain\Middleware\ExceptionsMiddleware
            - Apisearch\Server\Domain\Middleware\RepositoryReferenceMiddleware
            - Apisearch\Server\Domain\Middleware\CheckIndexAvailabilityMiddleware
            - Apisearch\Server\Domain\Middleware\TokenQueryMiddleware
            - Apisearch\Server\Domain\Middleware\CheckHealthPluginsMiddleware
            - Apisearch\Server\Domain\Middleware\ComplexFields\QueryComplexFieldsMiddleware
            - Apisearch\Server\Domain\Middleware\ComplexFields\GetIndicesComplexFieldsMiddleware
            - Apisearch\Server\Domain\Middleware\GetIndicesMetadataMiddleware
            - Apisearch\Server\Domain\Plugin\PluginMiddlewareCollector