services:

    #
    # Console commands
    #
    apisearch_server.command_with_command_bus_and_god_token:
        class: Apisearch\Server\Console\CommandWithBusAndGodToken
        abstract: true
        arguments:
            - "@apisearch_server.command_bus"
            - "@reactphp.event_loop"
            - "%apisearch_server.god_token%"

    apisearch_server.command_with_query_bus_and_god_token:
        class: Apisearch\Server\Console\CommandWithBusAndGodToken
        abstract: true
        arguments:
            - "@apisearch_server.query_bus"
            - "@reactphp.event_loop"
            - "%apisearch_server.god_token%"

    apisearch_server.configure_environment_command:
        class: Apisearch\Server\Console\ConfigureEnvironmentCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:configure-environment }

    apisearch_server.clean_environment_command:
        class: Apisearch\Server\Console\CleanEnvironmentCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:clean-environment }

    apisearch_server.create_index_command:
        class: Apisearch\Server\Console\CreateIndexCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        arguments:
            - "@apisearch.synonym_reader"
        tags:
            -  { name: console.command, command: apisearch-server:create-index }

    apisearch_server.configure_index_command:
        class: Apisearch\Server\Console\ConfigureIndexCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        arguments:
            - "@apisearch.synonym_reader"
        tags:
            -  { name: console.command, command: apisearch-server:configure-index }

    apisearch_server.delete_index_command:
        class: Apisearch\Server\Console\DeleteIndexCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:delete-index }

    apisearch_server.check_index_command:
        class: Apisearch\Server\Console\CheckIndexCommand
        parent: apisearch_server.command_with_query_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:check-index }

    apisearch_server.query_command:
        class: Apisearch\Server\Console\QueryCommand
        parent: apisearch_server.command_with_query_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:query }

    apisearch_server.add_token_command:
        class: Apisearch\Server\Console\AddTokenCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:add-token }

    apisearch_server.delete_token_command:
        class: Apisearch\Server\Console\DeleteTokenCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:delete-token }

    apisearch_server.delete_all_tokens_command:
        class: Apisearch\Server\Console\DeleteTokensCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:delete-all-tokens }

    apisearch_server.generate_basic_tokens_command:
        class: Apisearch\Server\Console\GenerateBasicTokensCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:generate-basic-tokens }

    apisearch_server.print_tokens_command:
        class: Apisearch\Server\Console\PrintTokensCommand
        parent: apisearch_server.command_with_query_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:print-tokens }

    apisearch_server.print_indices_command:
        class: Apisearch\Server\Console\PrintIndicesCommand
        parent: apisearch_server.command_with_query_bus_and_god_token
        tags:
        -  { name: console.command, command: apisearch-server:print-indices }

    apisearch_server.check_health_command:
        class: Apisearch\Server\Console\CheckHealthCommand
        parent: apisearch_server.command_with_query_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:check-health }

    apisearch_server.import_index_command:
        class: Apisearch\Server\Console\ImportIndexCommand
        parent: apisearch_server.command_with_query_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:import-index }

    apisearch_server.export_index_command:
        class: Apisearch\Server\Console\ExportIndexCommand
        parent: apisearch_server.command_with_query_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:export-index }

    apisearch_server.configuration:
        class: Apisearch\Server\Console\ServerConfigurationCommand
        arguments:
            - "@kernel"
        tags:
            -  { name: console.command, command: apisearch-server:server-configuration }

    apisearch_server.pause_consumers:
        class: Apisearch\Server\Console\PauseConsumersCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:pause-consumers }

    apisearch_server.resume_consumers:
        class: Apisearch\Server\Console\ResumeConsumersCommand
        parent: apisearch_server.command_with_command_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:resume-consumers }

    apisearch_server.generate_crontab:
        class: Apisearch\Server\Console\GenerateCrontabCommand
        parent: apisearch_server.command_with_query_bus_and_god_token
        tags:
            -  { name: console.command, command: apisearch-server:generate-crontab }

