#
# Token API
#
apisearch_v1_put_token:
    path: /v1/{app_id}/tokens/{token_id}
    methods: ["PUT"]
    controller: Apisearch\Server\Http\PutTokenController
    defaults:
        tags: tokens
        json: true

apisearch_v1_delete_token:
    path: /v1/{app_id}/tokens/{token_id}
    methods: ["DELETE"]
    controller: Apisearch\Server\Http\DeleteTokenController
    defaults:
        tags: tokens

apisearch_v1_get_tokens:
    path: /v1/{app_id}/tokens
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetTokensController
    defaults:
        tags: tokens
        json: true

apisearch_v1_delete_tokens:
    path: /v1/{app_id}/tokens
    methods: ["DELETE"]
    controller: Apisearch\Server\Http\DeleteTokensController
    defaults:
        tags: tokens
        json: true

#
# Index API
#
apisearch_v1_get_indices:
    path: /v1/{app_id}/indices
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetIndicesController
    defaults:
        tags: indices

apisearch_v1_create_index:
    path: /v1/{app_id}/indices/{index_id}
    methods: ["PUT"]
    controller: Apisearch\Server\Http\CreateIndexController
    defaults:
        tags: indices
        json: true

apisearch_v1_delete_index:
    path: /v1/{app_id}/indices/{index_id}
    methods: ["DELETE"]
    controller: Apisearch\Server\Http\DeleteIndexController
    defaults:
        tags: indices

apisearch_v1_reset_index:
    path: /v1/{app_id}/indices/{index_id}/reset
    methods: ["PUT", "POST"]
    controller: Apisearch\Server\Http\ResetIndexController
    defaults:
        tags: indices

apisearch_v1_configure_index:
    path: /v1/{app_id}/indices/{index_id}/configure
    methods: ["PUT", "POST"]
    controller: Apisearch\Server\Http\ConfigureIndexController
    defaults:
        tags: indices
        json: true

apisearch_v1_check_index:
    path: /v1/{app_id}/indices/{index_id}
    methods: ["HEAD"]
    controller: Apisearch\Server\Http\CheckIndexController
    defaults:
        tags: indices

apisearch_v1_export_index:
    path: /v1/{app_id}/indices/{index_id}/export
    methods: ["GET"]
    controller: Apisearch\Server\Http\ExportIndexController
    defaults:
        tags: indices, catalog

apisearch_v1_import_index_by_feed:
    path: /v1/{app_id}/indices/{index_id}/import/by-feed
    methods: ["PUT"]
    controller: Apisearch\Server\Http\ImportIndexByFeedController
    defaults:
        tags: indices, catalog

apisearch_v1_import_index_by_stream:
    path: /v1/{app_id}/indices/{index_id}/import/by-stream
    methods: ["PUT"]
    controller: Apisearch\Server\Http\ImportIndexByStreamController
    defaults:
        tags: indices, catalog

#
# Items API
#
apisearch_v1_put_items:
    path: /v1/{app_id}/indices/{index_id}/items
    methods: ["PUT"]
    controller: Apisearch\Server\Http\IndexItemsController
    defaults:
        tags: catalog
        json: true

apisearch_v1_update_items_by_query:
    path: /v1/{app_id}/indices/{index_id}/items/update-by-query
    methods: ["PUT", "POST"]
    controller: Apisearch\Server\Http\UpdateItemsByQueryController
    defaults:
        with_query: true
        tags: catalog
        json: true

apisearch_v1_delete_items:
    path: /v1/{app_id}/indices/{index_id}/items
    methods: ["DELETE"]
    controller: Apisearch\Server\Http\DeleteItemsController
    defaults:
        tags: catalog
        json: true

apisearch_v1_delete_items_by_query:
    path: /v1/{app_id}/indices/{index_id}/items/by-query
    methods: ["DELETE"]
    controller: Apisearch\Server\Http\DeleteItemsByQueryController
    defaults:
        with_query: true
        tags: catalog
        json: true

#
# Usage API
#
apisearch_v1_get_usage:
    path: /v1/{app_id}/usage
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetUsageController
    defaults:
        per_day: false
        tags: usage, metrics

apisearch_v1_get_usage_per_day:
    path: /v1/{app_id}/usage/per-day
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetUsageController
    defaults:
        per_day: true
        tags: usage, metrics

apisearch_v1_get_index_usage:
    path: /v1/{app_id}/indices/{index_id}/usage
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetUsageController
    defaults:
        per_day: false
        tags: usage, metrics

apisearch_v1_get_index_usage_per_day:
    path: /v1/{app_id}/indices/{index_id}/usage/per-day
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetUsageController
    defaults:
        per_day: true
        tags: usage, metrics


#
# Usage API CORS
#
apisearch_v1_get_usage_preflight:
    path: /v1/{app_id}/usage
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Http\QueryCORSController
    defaults:
        index_id: "*"

apisearch_v1_get_usage_per_day_preflight:
    path: /v1/{app_id}/usage/per-day
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Http\QueryCORSController
    defaults:
        index_id: "*"

apisearch_v1_get_index_usage_preflight:
    path: /v1/{app_id}/indices/{index_id}/usage
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Http\QueryCORSController

apisearch_v1_get_index_usage_per_day_preflight:
    path: /v1/{app_id}/indices/{index_id}/usage/per-day
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Http\QueryCORSController


#
# Query API
#
apisearch_v1_query:
    path: /v1/{app_id}/indices/{index_id}
    methods: ["GET"]
    controller: Apisearch\Server\Http\QueryController
    defaults:
        with_query: true
        tags: query

apisearch_v1_query_all_indices:
    path: /v1/{app_id}
    methods: ["GET"]
    controller: Apisearch\Server\Http\QueryController
    defaults:
        index_id: "*"
        with_query: true
        tags: query

#
# Query CORS API
#
apisearch_v1_query_preflight:
    path: /v1/{app_id}/indices/{index_id}
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Http\QueryCORSController

apisearch_v1_query_all_indices_preflight:
    path: /v1/{app_id}
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Http\QueryCORSController
    defaults:
        index_id: "*"

#
# Interaction API
#
apisearch_v1_post_click:
    path: /v1/{app_id}/indices/{index_id}/items/{item_id}/click
    methods: ["POST"]
    controller: Apisearch\Server\Http\PostClickController
    defaults:
        per_day: true
        tags: interactions, click, metrics
        json: true

apisearch_v1_post_click_preflight:
    path: /v1/{app_id}/indices/{index_id}/items/{item_id}/click
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Http\QueryCORSController
    defaults:
        allowed_method: POST

apisearch_v1_get_interactions:
    path: /v1/{app_id}/indices/{index_id}/interactions
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetInteractionsController
    defaults:
        per_day: false
        tags: interactions, metrics

apisearch_v1_get_interactions_all_indices:
    path: /v1/{app_id}/interactions
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetInteractionsController
    defaults:
        index_id: "*"
        per_day: false
        tags: interactions, metrics

apisearch_v1_get_interactions_per_day:
    path: /v1/{app_id}/indices/{index_id}/interactions/per-day
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetInteractionsController
    defaults:
        per_day: true
        tags: interactions, metrics

apisearch_v1_get_interactions_all_indices_per_day:
    path: /v1/{app_id}/interactions/per-day
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetInteractionsController
    defaults:
        index_id: "*"
        per_day: true
        tags: interactions, metrics

apisearch_v1_get_top_clicks:
    path: /v1/{app_id}/indices/{index_id}/top-clicks
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetTopInteractionsController
    defaults:
        tags: interactions, metrics

apisearch_v1_get_top_clicks_all_indices:
    path: /v1/{app_id}/top-clicks
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetTopInteractionsController
    defaults:
        index_id: "*"
        tags: interactions, metrics

        
#
# Searches API
#
apisearch_v1_get_searches:
    path: /v1/{app_id}/indices/{index_id}/searches
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetSearchesController
    defaults:
        per_day: false
        tags: searches, metrics

apisearch_v1_get_searches_all_indices:
    path: /v1/{app_id}/searches
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetSearchesController
    defaults:
        index_id: "*"
        per_day: false
        tags: searches, metrics

apisearch_v1_get_searches_per_day:
    path: /v1/{app_id}/indices/{index_id}/searches/per-day
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetSearchesController
    defaults:
        per_day: true
        tags: searches, metrics

apisearch_v1_get_searches_all_indices_per_day:
    path: /v1/{app_id}/searches/per-day
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetSearchesController
    defaults:
        index_id: "*"
        per_day: true
        tags: searches, metrics


apisearch_v1_get_top_searches:
    path: /v1/{app_id}/indices/{index_id}/top-searches
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetTopInteractionsController
    defaults:
        tags: searches, metrics

apisearch_v1_get_top_searches_all_indices:
    path: /v1/{app_id}/top-searches
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetTopSearchesController
    defaults:
        index_id: "*"
        tags: searches, metrics

#
# Metrics
#
apisearch_v1_get_metrics:
    path: /v1/{app_id}/indices/{index_id}/metrics
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetMetricsController
    defaults:
        tags: metrics

apisearch_v1_get_metrics_all_indices:
    path: /v1/{app_id}/metrics
    methods: ["GET"]
    controller: Apisearch\Server\Http\GetMetricsController
    defaults:
        index_id: "*"
        tags: metrics

apisearch_v1_get_metrics_preflight:
    path: /v1/{app_id}/indices/{index_id}/metrics
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Http\QueryCORSController

apisearch_v1_get_metrics_all_indices_preflight:
    path: /v1/{app_id}/metrics
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Http\QueryCORSController
    defaults:
        index_id: "*"

#
# Server API
#
apisearch_check_health:
    path: /health
    methods: ["GET"]
    controller: Apisearch\Server\Http\CheckHealthController
    defaults:
        firewall: admin

apisearch_ping:
    path: /
    methods: ["HEAD"]
    controller: Apisearch\Server\Http\PingController
    defaults:
        firewall: ping
