#
# Token API
#
apisearch_v1_put_token:
    path: /v1/{app_id}/tokens/{token_id}
    methods: ["PUT"]
    controller: Apisearch\Server\Controller\PutTokenController

apisearch_v1_delete_token:
    path: /v1/{app_id}/tokens/{token_id}
    methods: ["DELETE"]
    controller: Apisearch\Server\Controller\DeleteTokenController

apisearch_v1_get_tokens:
    path: /v1/{app_id}/tokens
    methods: ["GET"]
    controller: Apisearch\Server\Controller\GetTokensController

apisearch_v1_delete_tokens:
    path: /v1/{app_id}/tokens
    methods: ["DELETE"]
    controller: Apisearch\Server\Controller\DeleteTokensController

#
# Index API
#
apisearch_v1_get_indices:
    path: /v1/{app_id}/indices
    methods: ["GET"]
    controller: Apisearch\Server\Controller\GetIndicesController

apisearch_v1_create_index:
    path: /v1/{app_id}/indices/{index_id}
    methods: ["PUT"]
    controller: Apisearch\Server\Controller\CreateIndexController

apisearch_v1_delete_index:
    path: /v1/{app_id}/indices/{index_id}
    methods: ["DELETE"]
    controller: Apisearch\Server\Controller\DeleteIndexController

apisearch_v1_reset_index:
    path: /v1/{app_id}/indices/{index_id}/reset
    methods: ["PUT", "POST"]
    controller: Apisearch\Server\Controller\ResetIndexController

apisearch_v1_configure_index:
    path: /v1/{app_id}/indices/{index_id}/configure
    methods: ["PUT", "POST"]
    controller: Apisearch\Server\Controller\ConfigureIndexController

apisearch_v1_check_index:
    path: /v1/{app_id}/indices/{index_id}
    methods: ["HEAD"]
    controller: Apisearch\Server\Controller\CheckIndexController

apisearch_v1_export_index:
    path: /v1/{app_id}/indices/{index_id}/export
    methods: ["GET"]
    controller: Apisearch\Server\Controller\ExportIndexController

#
# Items API
#
apisearch_v1_put_items:
    path: /v1/{app_id}/indices/{index_id}/items
    methods: ["PUT"]
    controller: Apisearch\Server\Controller\IndexItemsController

apisearch_v1_update_items_by_query:
    path: /v1/{app_id}/indices/{index_id}/items/update-by-query
    methods: ["PUT", "POST"]
    controller: Apisearch\Server\Controller\UpdateItemsByQueryController

apisearch_v1_delete_items:
    path: /v1/{app_id}/indices/{index_id}/items
    methods: ["DELETE"]
    controller: Apisearch\Server\Controller\DeleteItemsController

#
# Usage API
#
apisearch_v1_get_usage:
    path: /v1/{app_id}/usage
    methods: ["GET"]
    controller: Apisearch\Server\Controller\GetUsageController
    defaults:
        per_day: false

apisearch_v1_get_usage_per_day:
    path: /v1/{app_id}/usage/per-day
    methods: ["GET"]
    controller: Apisearch\Server\Controller\GetUsageController
    defaults:
        per_day: true

apisearch_v1_get_index_usage:
    path: /v1/{app_id}/indices/{index_id}/usage
    methods: ["GET"]
    controller: Apisearch\Server\Controller\GetUsageController
    defaults:
        per_day: false

apisearch_v1_get_index_usage_per_day:
    path: /v1/{app_id}/indices/{index_id}/usage/per-day
    methods: ["GET"]
    controller: Apisearch\Server\Controller\GetUsageController
    defaults:
        per_day: true


#
# Usage API CORS
#
apisearch_v1_get_usage_preflight:
    path: /v1/{app_id}/usage
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Controller\QueryCORSController
    defaults:
        index_id: "*"

apisearch_v1_get_usage_per_day_preflight:
    path: /v1/{app_id}/usage/per-day
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Controller\QueryCORSController
    defaults:
        index_id: "*"

apisearch_v1_get_index_usage_preflight:
    path: /v1/{app_id}/indices/{index_id}/usage
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Controller\QueryCORSController

apisearch_v1_get_index_usage_per_day_preflight:
    path: /v1/{app_id}/indices/{index_id}/usage/per-day
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Controller\QueryCORSController


#
# Query API
#
apisearch_v1_query:
    path: /v1/{app_id}/indices/{index_id}
    methods: ["GET"]
    controller: Apisearch\Server\Controller\QueryController

apisearch_v1_query_all_indices:
    path: /v1/{app_id}
    methods: ["GET"]
    controller: Apisearch\Server\Controller\QueryController
    defaults:
        index_id: "*"

#
# Query CORS API
#
apisearch_v1_query_preflight:
    path: /v1/{app_id}/indices/{index_id}
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Controller\QueryCORSController

apisearch_v1_query_all_indices_preflight:
    path: /v1/{app_id}
    methods: ["OPTIONS"]
    controller: Apisearch\Server\Controller\QueryCORSController
    defaults:
        index_id: "*"

#
# Interaction API
#
apisearch_v1_post_interaction:
    path: /v1/{app_id}/interactions
    methods: ["POST"]
    controller: Apisearch\Server\Controller\AddInteractionController

#
# Server API
#
apisearch_check_health:
    path: /health
    methods: ["GET"]
    controller: Apisearch\Server\Controller\CheckHealthController
    defaults:
        firewall: admin

apisearch_ping:
    path: /
    methods: ["HEAD"]
    controller: Apisearch\Server\Controller\PingController
    defaults:
        firewall: ping
