services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $godToken: "%apisearch_server.god_token%"
            string $readonlyToken: "%apisearch_server.readonly_token%"
            string $healthCheckToken: "%apisearch_server.health_check_token%"
            string $pingToken: "%apisearch_server.ping_token%"
            int $numberOfResultsLimitation: "%apisearch_server.limitations_number_of_results%"
            int $defaultNumberOfSuggestions: "%apisearch_server.default_number_of_suggestions%"
            array $tokenEndpointPermissionsLimitation: "%apisearch_server.limitations_token_endpoint_permissions%"
            array $enabledPlugins: "%apisearch_server.enabled_plugins%"
            string $exchangeName: "%apisearch_server.async_events_exchange_name%"

    #
    # Aux services
    #
    React\HttpClient\Client:
    React\Http\Browser:

    #
    # Infrastructure
    #
    Apisearch\Server\Http\:
        resource: '../../Http/*Controller.php'
        tags: [ "controller.service_arguments" ]

    Apisearch\Server\Http\Listener\:
        resource: '../../Http/Listener/'

    Apisearch\Server\Console\:
        resource: '../../Console/'
        tags: [ "console.command" ]

    #
    # Domain
    #
    Apisearch\Server\Domain\CommandHandler\:
        resource: '../../Domain/CommandHandler/'
        tags: ["command_handler"]

    Apisearch\Server\Domain\QueryHandler\:
        resource: '../../Domain/QueryHandler/'
        tags: ["query_handler"]

    Apisearch\Server\Domain\Middleware\:
        resource: '../../Domain/Middleware/'

    Apisearch\Server\Domain\Listener\:
        resource: '../../Domain/Listener/'

    Apisearch\Server\Domain\Model\UserEncrypt:


    #
    # Repositories
    #
    Apisearch\Server\Domain\Repository\InMemoryRepository:
    Apisearch\Server\Domain\Repository\NoItemsInMemoryRepository:
    Apisearch\Server\Domain\Repository\AppRepository\IndexRepository:
        alias: Apisearch\Server\Domain\Repository\InMemoryRepository

    Apisearch\Server\Domain\Repository\Repository\ItemsRepository:
        alias: Apisearch\Server\Domain\Repository\InMemoryRepository

    Apisearch\Server\Domain\Repository\Repository\QueryRepository:
        alias: Apisearch\Server\Domain\Repository\InMemoryRepository

    # App Repositories
    Apisearch\Server\Domain\Repository\Repository\Repository:
    Apisearch\Server\Domain\Repository\AppRepository\Repository:

    # Token Repositories
    Apisearch\Server\Domain\Repository\AppRepository\EmptyTokenRepository:
    Apisearch\Server\Domain\Repository\AppRepository\InMemoryTokenRepository:
        tags:
            - { name: apisearch_server.token_locator }
            - { name: apisearch_server.token_provider }

    Apisearch\Server\Domain\Repository\AppRepository\TokenRepository:
        alias: Apisearch\Server\Domain\Repository\AppRepository\InMemoryTokenRepository

    # Config Repositories
    Apisearch\Server\Domain\Repository\AppRepository\ConfigRepository:
        class: Apisearch\Server\Domain\Repository\AppRepository\InMemoryConfigRepository

    # Usage Lines Repositories
    Apisearch\Server\Domain\Repository\UsageRepository\EmptyUsageRepository:
    Apisearch\Server\Domain\Repository\UsageRepository\InMemoryUsageRepository:
    Apisearch\Server\Domain\Repository\UsageRepository\TemporaryUsageRepository:
        alias: Apisearch\Server\Domain\Repository\UsageRepository\InMemoryUsageRepository

    Apisearch\Server\Domain\Repository\UsageRepository\UsageRepository:
        alias: Apisearch\Server\Domain\Repository\UsageRepository\EmptyUsageRepository

    # Metadata Repositories
    Apisearch\Server\Domain\Repository\MetadataRepository\InMemoryMetadataRepository:
    Apisearch\Server\Domain\Repository\MetadataRepository\DiskMetadataRepository:
        arguments:
            - "%apisearch_server.metadata_disk_repository_path%"
    Apisearch\Server\Domain\Repository\MetadataRepository\MetadataRepository:
        alias: Apisearch\Server\Domain\Repository\MetadataRepository\DiskMetadataRepository

    # Interaction Repositories
    Apisearch\Server\Domain\Repository\InteractionRepository\EmptyInteractionRepository:
    Apisearch\Server\Domain\Repository\InteractionRepository\InMemoryInteractionRepository:
    Apisearch\Server\Domain\Repository\InteractionRepository\TemporaryInteractionRepository:
        alias: Apisearch\Server\Domain\Repository\InteractionRepository\InMemoryInteractionRepository
    Apisearch\Server\Domain\Repository\InteractionRepository\InteractionRepository:
        alias: Apisearch\Server\Domain\Repository\InteractionRepository\InMemoryInteractionRepository

    # Searches Repositories
    Apisearch\Server\Domain\Repository\SearchesRepository\EmptySearchesRepository:
    Apisearch\Server\Domain\Repository\SearchesRepository\InMemorySearchesRepository:
    Apisearch\Server\Domain\Repository\SearchesRepository\TemporarySearchesRepository:
        alias: Apisearch\Server\Domain\Repository\SearchesRepository\InMemorySearchesRepository
    Apisearch\Server\Domain\Repository\SearchesRepository\SearchesRepository:
        alias: Apisearch\Server\Domain\Repository\SearchesRepository\EmptySearchesRepository

    #
    # Token
    #
    Apisearch\Server\Domain\Token\:
        resource: '../../Domain/Token/'

    Apisearch\Server\Domain\Token\StaticTokenLocator:
        tags:
            - { name: apisearch_server.token_locator }
            - { name: apisearch_server.token_provider }

    Apisearch\Server\Domain\Token\CredentialsTokenValidator:
        tags:
            - { name: apisearch_server.token_validator }

    #
    # Formatter
    #
    Apisearch\Server\Domain\Formatter\:
        resource: '../../Domain/Formatter/'

    #
    # Resources
    #
    Apisearch\Server\Domain\Resource\:
        resource: '../../Domain/Resource/'


    #
    # Format
    #
    Apisearch\Server\Domain\Format\StandardFormatTransformer:
    Apisearch\Server\Domain\Format\SourceFormatTransformer:
    Apisearch\Server\Domain\Format\FormatTransformers:
        calls:
            - [addFormatTransformer, ['@Apisearch\Server\Domain\Format\StandardFormatTransformer']]
            - [addFormatTransformer, ['@Apisearch\Server\Domain\Format\SourceFormatTransformer']]

    #
    # Plugin
    #
    Apisearch\Server\Domain\Plugin\PluginMiddlewareCollector:
