services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $godToken: "%apisearch_server.god_token%"
            string $readonlyToken: "%apisearch_server.readonly_token%"
            string $pingToken: "%apisearch_server.ping_token%"
            int $numberOfResultsLimitation: "%apisearch_server.limitations_number_of_results%"
            array $enabledPlugins: "%apisearch_server.enabled_plugins%"

    Apisearch\Server\Controller\:
        resource: '../../Controller'
        tags: ["controller.service_arguments"]

    Apisearch\Server\Console\:
        resource: '../../Console/'
        tags: ["console.command"]

    Apisearch\Server\Domain\CommandHandler\:
        resource: '../../Domain/CommandHandler/'
        tags: ["command_handler"]

    Apisearch\Server\Domain\QueryHandler\:
        resource: '../../Domain/QueryHandler/'
        tags: ["query_handler"]

    #
    # Domain Middlewares
    #
    Apisearch\Server\Domain\Middleware\:
        resource: '../../Domain/Middleware/'

    #
    # Event listeners
    #
    Apisearch\Server\Domain\Listener\:
        resource: '../../Domain/Listener/'


    #
    # Repositories
    #
    Apisearch\Server\Domain\Repository\InMemoryRepository:
    Apisearch\Server\Domain\Repository\AppRepository\IndexRepository:
        alias: Apisearch\Server\Domain\Repository\InMemoryRepository

    Apisearch\Server\Domain\Repository\Repository\ItemsRepository:
        alias: Apisearch\Server\Domain\Repository\InMemoryRepository

    Apisearch\Server\Domain\Repository\Repository\QueryRepository:
        alias: Apisearch\Server\Domain\Repository\InMemoryRepository

    Apisearch\Server\Domain\Repository\Repository\Repository:
    Apisearch\Server\Domain\Repository\AppRepository\Repository:
    Apisearch\Server\Domain\Repository\AppRepository\TokenRepository:
        class: Apisearch\Server\Domain\Repository\AppRepository\InMemoryTokenRepository
        tags:
            - { name: apisearch_server.token_locator }
            - { name: apisearch_server.token_provider }
    Apisearch\Server\Domain\Repository\AppRepository\InMemoryTokenRepository:
        alias: Apisearch\Server\Domain\Repository\AppRepository\TokenRepository

    Apisearch\Server\Domain\Repository\AppRepository\ConfigRepository:
        class: Apisearch\Server\Domain\Repository\AppRepository\InMemoryConfigRepository

    Apisearch\Server\Domain\Repository\UsageRepository\EmptyUsageRepository:
    Apisearch\Server\Domain\Repository\UsageRepository\InMemoryUsageRepository:
    Apisearch\Server\Domain\Repository\UsageRepository\TemporaryUsageRepository:
        alias: Apisearch\Server\Domain\Repository\UsageRepository\InMemoryUsageRepository

    Apisearch\Server\Domain\Repository\UsageRepository\UsageRepository:
        alias: Apisearch\Server\Domain\Repository\UsageRepository\EmptyUsageRepository

    Apisearch\Server\Domain\Repository\MetadataRepository\InMemoryMetadataRepository:
    Apisearch\Server\Domain\Repository\MetadataRepository\MetadataRepository:
        alias: Apisearch\Server\Domain\Repository\MetadataRepository\InMemoryMetadataRepository

    Apisearch\Server\Domain\Repository\InteractionRepository\InMemoryInteractionRepository:
    Apisearch\Server\Domain\Repository\InteractionRepository\TemporaryInteractionRepository:
        alias: Apisearch\Server\Domain\Repository\InteractionRepository\InMemoryInteractionRepository
    Apisearch\Server\Domain\Repository\InteractionRepository\InteractionRepository:
        alias: Apisearch\Server\Domain\Repository\InteractionRepository\InMemoryInteractionRepository

    Apisearch\Server\Domain\Repository\SearchesRepository\EmptySearchesRepository:
    Apisearch\Server\Domain\Repository\SearchesRepository\InMemorySearchesRepository:
    Apisearch\Server\Domain\Repository\SearchesRepository\TemporarySearchesRepository:
        alias: Apisearch\Server\Domain\Repository\SearchesRepository\InMemorySearchesRepository
    Apisearch\Server\Domain\Repository\SearchesRepository\SearchesRepository:
        alias: Apisearch\Server\Domain\Repository\SearchesRepository\EmptySearchesRepository

    #
    # Token
    #
    Apisearch\Server\Domain\Token\:
        resource: '../../Domain/Token/'

    Apisearch\Server\Domain\Token\StaticTokenLocator:
        tags:
            - { name: apisearch_server.token_locator }
            - { name: apisearch_server.token_provider }

    Apisearch\Server\Domain\Token\CredentialsTokenValidator:
        tags:
            - { name: apisearch_server.token_validator }

    #
    # Formatter
    #
    Apisearch\Server\Domain\Formatter\:
        resource: '../../Domain/Formatter/'

    #
    # Plugin
    #
    Apisearch\Server\Domain\Plugin\PluginMiddlewareCollector: