tactician:
    default_bus: command
    commandbus:
        command:
            middleware:
                - tactician.middleware.locking
                - apisearch_server.middleware.exceptions
                - apisearch_server.middleware.repository_reference
                - apisearch_server.middleware.plugins
                - tactician.middleware.command_handler

        query:
            middleware:
                - apisearch_server.middleware.exceptions
                - apisearch_server.middleware.repository_reference
                - apisearch_server.middleware.token_query
                - apisearch_server.middleware.plugins
                - tactician.middleware.command_handler