tactician:
    default_bus: command
    commandbus:
        command:
            middleware:
                - tactician.middleware.locking
                - apisearch_server.middleware.exceptions
                - apisearch_server.middleware.repository_reference
                - apisearch_server.middleware.plugins
                - tactician.middleware.command_handler

        async_command:
            middleware:
                - tactician.middleware.locking
                - apisearch_server.middleware.exceptions
                - apisearch_server.middleware.repository_reference
                - apisearch_server.middleware.async_commands
                - apisearch_server.middleware.plugins
                - tactician.middleware.command_handler

        query:
            middleware:
                - apisearch_server.middleware.exceptions
                - apisearch_server.middleware.repository_reference
                - apisearch_server.middleware.token_query
                - apisearch_server.middleware.plugins
                - tactician.middleware.command_handler
services:

    apisearch_server.command_bus:
        alias: tactician.commandbus.command
        public: false

    apisearch_server.async_command_bus:
        alias: tactician.commandbus.async_command
        public: false

    apisearch_server.query_bus:
        alias: tactician.commandbus.query
        public: false