imports:
    - { resource: "@ApisearchServerBundle/Resources/config/command_bus.yml"}
    - { resource: '../../.deploy/*.{yml,yaml}' }

parameters:
    kernel.secret: nsdjkfhdsupoifjñksd

framework:
    form: false
    assets: false
    esi: false
    session: false
    translator: false
    profiler: false
    validation: false
    fragments: false
    csrf_protection: false
    secret: false
    php_errors:
        log: false
    router:
        utf8: true

apisearch:
    load_commands: false

#
# Preload Bundle configuration
#
preload:
    services:
        "amqp.event_bus_channel": ~
        "amqp.command_bus_channel": ~
    presets:
        - "@symfony"
        - "@drift"
        - "@react"
