imports:
    - { resource: "@ApisearchServerBundle/Resources/config/command_bus.yml"}

parameters:
    kernel.secret: nsdjkfhdsupoifjñksd

framework:
    form: false
    assets: false
    esi: false
    session: false
    translator: false
    profiler: false
    validation: false
    fragments: false
    csrf_protection: false
    secret: false
    php_errors:
        log: false

apisearch:
    load_commands: false
