# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
general:
    branches:
        ignore:
            - docker-image/*
jobs:
    with-infrastructure:
        docker:
            -   image: circleci/php:7.4.4-cli
            -   image: rabbitmq:3-alpine
            -   image: redis:4-alpine
            -   image: docker.elastic.co/elasticsearch/elasticsearch:6.1.4
                name: apisearch.elasticsearch.6.1
                environment:
                    ES_JAVA_OPTS: -Xms256m -Xmx256m
                    discovery.type: single-node
                    action.auto_create_index: -apisearch*,+*
            -   image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
                name: apisearch.elasticsearch.6.8
                environment:
                    ES_JAVA_OPTS: -Xms256m -Xmx256m
                    discovery.type: single-node
                    action.auto_create_index: -apisearch*,+*
            -   image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
                name: apisearch.elasticsearch.7.0
                environment:
                    ES_JAVA_OPTS: -Xms256m -Xmx256m
                    discovery.type: single-node
                    action.auto_create_index: -apisearch*,+*
            -   image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
                environment:
                    ES_JAVA_OPTS: -Xms256m -Xmx256m
                    discovery.type: single-node
                    action.auto_create_index: -apisearch*,+*

        working_directory: ~/project
        steps:
            -   checkout
            -   run:
                    name: Install dependencies
                    command: |
                        sudo docker-php-ext-install pcntl
                        sudo apt install -y git

            -   run:
                    name: Load dev dependencies
                    command: |
                        composer install -n --no-suggest

            -   run:
                    name: Run tests
                    command: |
                        php vendor/bin/phpunit --testsuite plugins


    without-infrastructure:
        docker:
            -   image: docker:stable

        working_directory: ~/
        steps:
            -   checkout
            -   setup_remote_docker:
                    docker_layer_caching: false

            -   run:
                    name: Build Apisearch
                    command: |
                        docker build -t apisearch/server .

            -   run:
                    name: Run tests
                    command: |
                        docker run apisearch/server sh .circleci/scripts/run-domain-tests

workflows:
    version: 2
    test:
        jobs:
            - with-infrastructure
            - without-infrastructure