version: '3'

services:
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.0"
        ports:
            - "9200:9200"
        environment:
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
            - "discovery.type=single-node"
            - "action.auto_create_index=-apisearch*,+*"
