version: '3'

services:

    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.0"
        ports:
            - "9200:9200"
        environment:
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
            - "discovery.type=single-node"
            - "action.auto_create_index=-apisearch*,+*"

    elasticsearch_legacy:
        image: "docker.elastic.co/elasticsearch/elasticsearch:6.1.4"
        ports:
            - "9201:9200"
        environment:
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
            - "discovery.type=single-node"
            - "action.auto_create_index=-apisearch*,+*"

    amqp:
        image: "rabbitmq:3-management"
        ports:
            - "5672:5672"
            - "15672:15672"

    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"

    mysql:
        image: mysql:5
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: apisearch
