version: '3'

services:

    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.0"
        networks: [apisearch]
        ports:
            - "9200:9200"
        environment:
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
            - "discovery.type=single-node"
            - "action.auto_create_index=-apisearch*,+*"

    amqp:
        image: "rabbitmq:3-management"
        networks: [apisearch]
        ports:
            - "5672:5672"
            - "15672:15672"

    redis:
        image: "redis:alpine"
        networks: [apisearch]
        ports:
            - "6379:6379"

    postgresql:
        image: postgres:alpine
        networks: [apisearch]
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: apisearch
networks:
    apisearch: